{{- if .Values.gateway.enabled -}}
{{- $fullName := include "flex.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $pathType := .Values.gateway.pathType -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "flex.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.gatewayName }}
    {{- if .Values.gateway.gatewayNamespace }}
    namespace: {{ .Values.gateway.gatewayNamespace }}
    {{- end }}
  {{- if .Values.gateway.hosts }}
  hostnames:
    {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.hosts }}
    {{- range .paths }}
    - matches:
      - path:
          type: {{ $pathType }}
          value: {{ . | quote }}
      backendRefs:
      - name: {{ $fullName }}
        port: {{ $svcPort }}
    {{- end }}
    {{- end }}
{{- end }}
