replicaCount: 1

image:
  repository: factorhouse/kpow-ce
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

env: { }
envFromConfigMap: null
envFromSecret: null
volumeMounts: [ ]
# - name: rbac-config
#   mountPath: /path/to/rbac-config.yaml
#   subPath: rbac-config.yaml
volumes: [ ]
# - name: rbac-config
#   configMap:
#     name: "my-kpow-ce-config"

ephemeralTmp:
  # Sets up an emptyDir volume mount for Snappy compression and other features requiring /tmp access.
  # Enable this if you use Snappy compression and you have readOnly filesystem Pod policies.
  enabled: false
  volumeMount:
    name: "fh-tmp"
    mountPath: "/opt/factorhouse/tmp"
  volume:
    emptyDir:
      medium: Memory # Optional: for better performance
      sizeLimit: "100Mi" # Configurable size

serviceAccount:
  create: true
  annotations: { }
  name: kpow-ce

podAnnotations: { }

podSecurityContext: { }

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
      - ALL

service:
  enabled: true
  annotations: { }
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: { }
  hosts: [ ]
  tls: [ ]
  ingressClassName: ""

# We recommend running Kpow Community w/ Guaranteed QOS
# For a single cluster you can modify to 0.5CPU, 2GB heap, monitor performance afterwards and adjust as necessary.
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

nodeSelector: { }

tolerations: [ ]

affinity: { }

labels: { }
