name: Release Charts

on:
  push:
    branches:
      - main
      - feature/FAC-158_gain-more-artifacthub-recognition

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare for Chart Releaser
        run: |
          # Create a passphrase file for chart-releaser to use for signing
          echo "$GPG_PASSPHRASE" > passphrase.txt

          # Create the .cr.yaml config file using the key ID from the import step
          cat <<EOF > .cr.yaml
          sign: true
          key: "${{ steps.import_gpg.outputs.keyid }}"
          keyring: "/home/runner/.gnupg/pubring.kbx"
          passphrase-file: "passphrase.txt"
          EOF
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}          
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
